### PR TITLE
Fixed issue caused when multiple BMPs have been connected

### PR DESCRIPTION
**Pull request by sidprice**
The find_bmp method assumed only a single BMP had ever been connected to the computer. This PR fixes this issue.

### CODE REVIEW

**Comment by compuphase** [comment]
Thank you for the fix. I have not been able to check it yet (because so far I failed to upgrade my cheap ST-Link v2 clone to a BMP). As an aside: thanks for the blog on compiling the BMP firmware on WIndows 10. That has been a great help.

**Comment by sidprice** [comment]
@compuphase Happy the blog was useful. More recently I have set up VSCode to build and debug BMP code, and of course my [ctxLink probe](www.crowdsupply.com/sid-price/ctxlink).

**Comment by sidprice** [comment]
@compuphase , I have recently also setup VSCode to build and debug BMP and my ctxLink probe.

Take a look at [Crowd Supply](https://www.crowdsupply.com/sid-price/ctxlink)

**Comment by compuphase** [comment]
I saw the ctxLink probe. It looks like a step forward from the BMP. I have not yet decided whether I want one (but I still have 30 days...).

**Pull request merged**
